(function(){
  var STORAGE_KEY="copaChigui.activeUniverse.v001";
  var SLOT_PREFIX="copaChigui.slot.";
  var teams=window.COPA_CHIGUI_TEAMS||[];
  var mainMenu=document.getElementById("mainMenuScreen");
  if(!mainMenu){return;}

  function read(){try{var raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):null;}catch(e){return null;}}
  function write(u){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(u));return true;}catch(e){return false;}}
  function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");}
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function byId(cup,id){return cup&&cup.participants?(cup.participants.find(function(t){return t.id===id;})||null):null;}
  function outcome(a,b){return a>b?"H":b>a?"A":"D";}
  function ensureMeta(u){
    u.coins=Number(u.coins)||0;
    u.meta=u.meta||{};
    u.meta.shop=u.meta.shop||{owned:{classic:true},activeTheme:"classic",activeTrophy:"trophy"};
    u.meta.shop.owned=u.meta.shop.owned||{classic:true};
    u.meta.rewards=u.meta.rewards||{keys:{}};
    u.meta.rewards.keys=u.meta.rewards.keys||{};
    u.meta.settings=u.meta.settings||{sound:true,animations:true};
    u.meta.achievements=u.meta.achievements||{};
    return u.meta;
  }
  function toast(text){var old=document.querySelector(".coin-reward-toast");if(old){old.remove();}var el=document.createElement("div");el.className="coin-reward-toast";el.textContent=text;document.body.appendChild(el);setTimeout(function(){el.remove();},2600);}
  function reward(u,key,amount,label){ensureMeta(u);if(u.meta.rewards.keys[key]){return false;}u.meta.rewards.keys[key]=true;u.coins+=amount;if(label){toast("🪙 +"+amount+" · "+label);}return true;}
  function allMatches(cup){var list=[];(cup.groups||[]).forEach(function(g){(g.matchdays||[]).forEach(function(d){(d.matches||[]).forEach(function(m){list.push(m);});});});["roundOf32","roundOf16","quarterfinals","semifinals","thirdPlace","final"].forEach(function(k){var r=cup.knockout&&Array.isArray(cup.knockout[k])?cup.knockout[k]:[];r.forEach(function(m){list.push(m);});});return list;}
  function groupDone(cup){var m=0,c=0;(cup.groups||[]).forEach(function(g){(g.matchdays||[]).forEach(function(d){(d.matches||[]).forEach(function(x){m++;if(x.completed)c++;});});});return m>0&&m===c;}
  function processRewards(showToast){var u=read();if(!u||!u.cup){return;}ensureMeta(u);var changed=false;changed=reward(u,"universe-created",150,showToast?"Primera historia creada":null)||changed;if(groupDone(u.cup)){changed=reward(u,"groups-"+(u.cup.edition||1),200,showToast?"Fase de grupos completada":null)||changed;}if(u.cup.completed){changed=reward(u,"cup-"+(u.cup.edition||1),500,showToast?"Copa terminada":null)||changed;}
    var pred=u.cup.predictions&&u.cup.predictions.entries?u.cup.predictions.entries:{};
    allMatches(u.cup).forEach(function(m){var e=pred[m.id];if(!m.completed||!e||!e.player){return;}var exact=Number(e.player.home)===Number(m.homeGoals)&&Number(e.player.away)===Number(m.awayGoals);var correct=outcome(Number(e.player.home),Number(e.player.away))===outcome(Number(m.homeGoals),Number(m.awayGoals));var amount=exact?100:(correct?30:0);if(amount){changed=reward(u,"prediction-"+(u.cup.edition||1)+"-"+m.id,amount,showToast?(exact?"Marcador exacto":"Resultado acertado"):null)||changed;}});
    if(changed){write(u);}applyCosmetics(u);updateWallet(u);
  }

  var achievements=[
    {id:"first-story",icon:"🌍",name:"Nueva historia",desc:"Crear tu primer universo.",test:function(u){return !!u.cup;}},
    {id:"groups",icon:"📋",name:"64 en marcha",desc:"Completar una fase de grupos.",test:function(u){return groupDone(u.cup);}},
    {id:"cup",icon:"🏆",name:"Historia escrita",desc:"Completar una Copa Chigui.",test:function(u){return !!u.cup.completed;}},
    {id:"exact",icon:"🎯",name:"En el marcador",desc:"Acertar un resultado exacto.",test:function(u){var p=u.cup.predictions&&u.cup.predictions.entries||{};return allMatches(u.cup).some(function(m){var e=p[m.id];return m.completed&&e&&e.player&&Number(e.player.home)===Number(m.homeGoals)&&Number(e.player.away)===Number(m.awayGoals);});}},
    {id:"host-run",icon:"🏟️",name:"Orgullo local",desc:"Que el anfitrión alcance semifinales.",test:function(u){var c=u.cup;var sf=c.knockout&&c.knockout.semifinals||[];return sf.some(function(m){return m.homeId===c.hostId||m.awayId===c.hostId;});}},
    {id:"champ-host",icon:"👑",name:"Campeón en casa",desc:"Que el anfitrión gane la Copa.",test:function(u){return u.cup.completed&&u.cup.championId===u.cup.hostId;}}
  ];
  function syncAchievements(){var u=read();if(!u||!u.cup)return;ensureMeta(u);var changed=false;achievements.forEach(function(a){if(a.test(u)&&!u.meta.achievements[a.id]){u.meta.achievements[a.id]=new Date().toISOString();changed=true;}});if(changed)write(u);}

  function updateWallet(u){u=u||read();var el=document.getElementById("mainWalletAmount");if(el){el.textContent=(u?Number(u.coins)||0:0)+" Chigui Coins";}}
  function applyCosmetics(u){u=u||read();if(!u){document.body.dataset.chiguiTheme="classic";return;}var meta=ensureMeta(u);document.body.dataset.chiguiTheme=meta.shop.activeTheme||"classic";document.body.classList.toggle("chigui-no-animations",meta.settings.animations===false);var trophy=document.querySelector(".hero .trophy");if(trophy){var icons={trophy:"🏆",crown:"👑",star:"⭐",ball:"⚽"};trophy.textContent=icons[meta.shop.activeTrophy]||"🏆";}}

  function makeOverlay(id,title){var old=document.getElementById(id);if(old)return old;var o=document.createElement("div");o.id=id;o.className="hub-overlay hidden";o.innerHTML='<div class="hub-dialog"><header class="hub-header"><div><p class="eyebrow">COPA CHIGUI</p><h2>'+esc(title)+'</h2></div><button class="secondary-button hub-close" type="button">✕ Cerrar</button></header><div class="hub-body"></div></div>';document.body.appendChild(o);o.querySelector(".hub-close").addEventListener("click",function(){o.classList.add("hidden");document.body.style.overflow="";});o.addEventListener("click",function(e){if(e.target===o){o.classList.add("hidden");document.body.style.overflow="";}});return o;}
  function openOverlay(o){o.classList.remove("hidden");document.body.style.overflow="hidden";}

  function cupsFor(u){var arr=[];(u.history||[]).forEach(function(h){if(h.cup)arr.push(h.cup);});if(u.cup&&!arr.some(function(c){return Number(c.edition)===Number(u.cup.edition);})){arr.push(u.cup);}return arr;}
  function statsForTeam(u,id){var s={pj:0,w:0,d:0,l:0,gf:0,ga:0,titles:0,participations:0,best:"—",rank:"—",points:100};var stages=[];cupsFor(u).forEach(function(c){if(!(c.participants||[]).some(function(t){return t.id===id;}))return;s.participations++;allMatches(c).forEach(function(m){if(!m.completed||(m.homeId!==id&&m.awayId!==id))return;var home=m.homeId===id,hg=Number(m.homeGoals),ag=Number(m.awayGoals),gf=home?hg:ag,ga=home?ag:hg;s.pj++;s.gf+=gf;s.ga+=ga;if(m.winnerId){if(m.winnerId===id)s.w++;else s.l++;}else if(gf>ga)s.w++;else if(gf<ga)s.l++;else s.d++;});if(c.championId===id){s.titles++;stages.push(1);}else if(c.runnerUpId===id)stages.push(2);else if(c.thirdPlaceId===id)stages.push(3);else if(c.knockout&&c.knockout.semifinals&&c.knockout.semifinals.some(function(m){return m.homeId===id||m.awayId===id;}))stages.push(4);});if(stages.length){var b=Math.min.apply(Math,stages);s.best=b===1?"Campeón":b===2?"Subcampeón":b===3?"Tercer lugar":"Semifinales";}var r=u.cup.worldRankingTeams||[];var rt=r.find(function(t){return t.id===id;});if(rt){s.rank="#"+(rt.currentRank||"—");s.points=rt.points;s.titles=Math.max(s.titles,rt.titles||0);}return s;}
  function h2h(u,a,b){var r={a:0,b:0,d:0,total:0};cupsFor(u).forEach(function(c){allMatches(c).forEach(function(m){if(!m.completed)return;var pair=(m.homeId===a&&m.awayId===b)||(m.homeId===b&&m.awayId===a);if(!pair)return;r.total++;if(m.winnerId){if(m.winnerId===a)r.a++;else r.b++;}else{var hg=Number(m.homeGoals),ag=Number(m.awayGoals);if(hg===ag)r.d++;else{var w=hg>ag?m.homeId:m.awayId;if(w===a)r.a++;else r.b++;}}});});return r;}

  function showTeams(){var u=read();if(!u)return;var o=makeOverlay("teamBrowserOverlay","Selecciones");var body=o.querySelector(".hub-body");body.innerHTML='<div class="hub-toolbar"><input id="teamHubSearch" type="search" placeholder="Buscar selección..."></div><div id="teamHubContent"></div>';var input=body.querySelector("#teamHubSearch"),content=body.querySelector("#teamHubContent");function renderList(){var q=input.value.trim().toLowerCase();var visible=teams.filter(function(t){return !q||t.name.toLowerCase().indexOf(q)!==-1;}).slice(0,120);content.innerHTML='<div class="team-browser-list">'+visible.map(function(t){return '<button class="team-browser-button" data-team="'+esc(t.id)+'"><span>'+esc(t.flag||"🏳️")+'</span><span>'+esc(t.name)+'</span></button>';}).join("")+'</div>';content.querySelectorAll("[data-team]").forEach(function(b){b.addEventListener("click",function(){showTeamProfile(b.dataset.team,o);});});}input.addEventListener("input",renderList);renderList();openOverlay(o);}
  function showTeamProfile(id,parent){var u=read();var base=teams.find(function(t){return t.id===id;})||byId(u.cup,id);if(!base)return;var s=statsForTeam(u,id);var o=makeOverlay("teamProfileOverlay","Perfil de selección");var body=o.querySelector(".hub-body");var opponents=teams.filter(function(t){return t.id!==id;});body.innerHTML='<div class="team-profile-hero"><div class="profile-flag">'+esc(base.flag||"🏳️")+'</div><div class="team-profile-name"><h2>'+esc(base.name)+(s.titles?' '+"⭐".repeat(Math.min(s.titles,5)):'')+'</h2><span class="muted">'+esc(base.confederation||"")+'</span></div><div class="team-profile-score"><strong>'+esc(s.points)+' pts</strong><span>'+esc(s.rank)+'</span></div></div><div class="hub-grid"><div class="hub-card"><h3>📊 Historial</h3><div class="hub-stat"><span>Participaciones</span><strong>'+s.participations+'</strong></div><div class="hub-stat"><span>Títulos</span><strong>'+s.titles+'</strong></div><div class="hub-stat"><span>Mejor resultado</span><strong>'+esc(s.best)+'</strong></div></div><div class="hub-card"><h3>⚽ Partidos</h3><div class="hub-stat"><span>PJ</span><strong>'+s.pj+'</strong></div><div class="hub-stat"><span>G / E / P</span><strong>'+s.w+' / '+s.d+' / '+s.l+'</strong></div><div class="hub-stat"><span>GF / GC</span><strong>'+s.gf+' / '+s.ga+'</strong></div></div><div class="hub-card"><h3>⚔️ Cara a cara</h3><select id="h2hOpponent"><option value="">Elige rival...</option>'+opponents.map(function(t){return '<option value="'+esc(t.id)+'">'+esc(t.name)+'</option>';}).join("")+'</select><div id="h2hResult" class="muted" style="margin-top:10px">Consulta el historial contra otra selección.</div></div></div>';body.querySelector("#h2hOpponent").addEventListener("change",function(){var rid=this.value,res=body.querySelector("#h2hResult");if(!rid){res.textContent="Consulta el historial contra otra selección.";return;}var r=h2h(u,id,rid),opp=teams.find(function(t){return t.id===rid;});res.innerHTML='<strong>'+esc(base.name)+' '+r.a+' · '+r.d+' empates · '+r.b+' '+esc(opp?opp.name:rid)+'</strong><br>'+r.total+' enfrentamientos registrados';});openOverlay(o);}

  function cupStats(cup){var map={};(cup.participants||[]).forEach(function(t){map[t.id]={id:t.id,name:t.name,flag:t.flag,pj:0,w:0,d:0,l:0,gf:0,ga:0};});allMatches(cup).forEach(function(m){if(!m.completed||!map[m.homeId]||!map[m.awayId])return;var h=map[m.homeId],a=map[m.awayId],hg=Number(m.homeGoals),ag=Number(m.awayGoals);h.pj++;a.pj++;h.gf+=hg;h.ga+=ag;a.gf+=ag;a.ga+=hg;if(m.winnerId){if(m.winnerId===h.id){h.w++;a.l++;}else{a.w++;h.l++;}}else if(hg>ag){h.w++;a.l++;}else if(ag>hg){a.w++;h.l++;}else{h.d++;a.d++;}});return Object.keys(map).map(function(k){return map[k];});}
  function recordData(u){var all=[];cupsFor(u).forEach(function(c){allMatches(c).forEach(function(m){if(m.completed)all.push({cup:c,match:m});});});var biggest=null;all.forEach(function(x){var d=Math.abs(Number(x.match.homeGoals)-Number(x.match.awayGoals));if(!biggest||d>biggest.diff){biggest={diff:d,x:x};}});var wins={};teams.forEach(function(t){wins[t.id]=0;});all.forEach(function(x){var m=x.match;if(m.winnerId){wins[m.winnerId]=(wins[m.winnerId]||0)+1;}else{var hg=Number(m.homeGoals),ag=Number(m.awayGoals);if(hg!==ag){var id=hg>ag?m.homeId:m.awayId;wins[id]=(wins[id]||0)+1;}}});var mostWins=teams.slice().sort(function(a,b){return (wins[b.id]||0)-(wins[a.id]||0);})[0];var ranking=u.cup.worldRankingTeams||[];var mostTitles=ranking.slice().sort(function(a,b){return (b.titles||0)-(a.titles||0);})[0];return{biggest:biggest,mostWins:mostWins,wins:wins,mostTitles:mostTitles};}
  function labelTeam(cup,id){var t=byId(cup,id)||teams.find(function(x){return x.id===id;});return t?(t.flag||"🏳️")+" "+t.name:id;}
  function latestNews(u){var c=u.cup,done=[];allMatches(c).forEach(function(m){if(m.completed)done.push(m);});done=done.slice(-5).reverse();if(!done.length)return ["La Copa está lista. Todavía no se han jugado partidos."];return done.map(function(m){var hg=Number(m.homeGoals),ag=Number(m.awayGoals),h=labelTeam(c,m.homeId),a=labelTeam(c,m.awayId);if(Math.abs(hg-ag)>=4)return "💥 Goleada: "+h+" "+hg+"-"+ag+" "+a;return "⚽ Resultado: "+h+" "+hg+"-"+ag+" "+a;});}
  function showRecords(){var u=read();if(!u)return;syncAchievements();u=read();var o=makeOverlay("recordsOverlay","Récords, premios y logros");var body=o.querySelector(".hub-body"),r=recordData(u),cs=cupStats(u.cup);var attack=cs.slice().sort(function(a,b){return b.gf-a.gf;})[0],defense=cs.slice().sort(function(a,b){return a.ga-b.ga;})[0],winner=cs.slice().sort(function(a,b){return b.w-a.w;})[0];var big="Sin partidos";if(r.biggest){var m=r.biggest.x.match,c=r.biggest.x.cup;big=labelTeam(c,m.homeId)+" "+m.homeGoals+"-"+m.awayGoals+" "+labelTeam(c,m.awayId);}var mostWins=r.mostWins?(r.mostWins.flag+" "+r.mostWins.name+" · "+(r.wins[r.mostWins.id]||0)+" victorias"):"—";var titles=r.mostTitles?((r.mostTitles.flag||"🏳️")+" "+r.mostTitles.name+" · "+(r.mostTitles.titles||0)+" títulos"):"—";body.innerHTML='<div class="hub-tabs"><button class="hub-tab active" data-tab="records">Récords</button><button class="hub-tab" data-tab="awards">Premios</button><button class="hub-tab" data-tab="news">Noticias</button><button class="hub-tab" data-tab="achievements">Logros</button></div><div class="hub-section" data-section="records"><div class="hub-grid"><div class="hub-card record-highlight"><h3>💥 Mayor goleada</h3><div class="record-value">'+esc(big)+'</div></div><div class="hub-card"><h3>🏆 Más títulos</h3><div class="record-value">'+esc(titles)+'</div></div><div class="hub-card"><h3>✅ Más victorias</h3><div class="record-value">'+esc(mostWins)+'</div></div></div></div><div class="hub-section hidden" data-section="awards"><div class="awards-grid"><div class="award-card"><h3>🔥 Mejor ataque</h3><strong>'+esc(attack?attack.flag+" "+attack.name:"—")+'</strong><p>'+esc(attack?attack.gf:0)+' goles</p></div><div class="award-card"><h3>🧤 Mejor defensa</h3><strong>'+esc(defense?defense.flag+" "+defense.name:"—")+'</strong><p>'+esc(defense?defense.ga:0)+' recibidos</p></div><div class="award-card"><h3>💪 Más victorias</h3><strong>'+esc(winner?winner.flag+" "+winner.name:"—")+'</strong><p>'+esc(winner?winner.w:0)+' triunfos</p></div></div></div><div class="hub-section hidden" data-section="news"><div class="news-list">'+latestNews(u).map(function(n){return '<div class="news-item">'+esc(n)+'</div>';}).join("")+'</div></div><div class="hub-section hidden" data-section="achievements"><div class="achievement-grid">'+achievements.map(function(a){var ok=!!u.meta.achievements[a.id];return '<div class="achievement-card '+(ok?'is-unlocked':'is-locked')+'"><h3>'+a.icon+' '+esc(a.name)+'</h3><p>'+esc(a.desc)+'</p><strong>'+(ok?'✅ Desbloqueado':'🔒 Pendiente')+'</strong></div>';}).join("")+'</div></div>';body.querySelectorAll(".hub-tab").forEach(function(b){b.addEventListener("click",function(){body.querySelectorAll(".hub-tab").forEach(function(x){x.classList.toggle("active",x===b);});body.querySelectorAll(".hub-section").forEach(function(s){s.classList.toggle("hidden",s.dataset.section!==b.dataset.tab);});});});openOverlay(o);}

  var shopItems=[
    {id:"classic",type:"theme",name:"Verde clásico",price:0,a:"#1b2844",b:"#59d28b"},
    {id:"ocean",type:"theme",name:"Océano",price:250,a:"#0a2637",b:"#4ec5f1"},
    {id:"violet",type:"theme",name:"Violeta",price:350,a:"#211734",b:"#b18cff"},
    {id:"gold",type:"theme",name:"Campeón dorado",price:500,a:"#2a2213",b:"#f0c65a"},
    {id:"midnight",type:"theme",name:"Medianoche",price:650,a:"#080d1b",b:"#80a5ff"},
    {id:"crown",type:"trophy",name:"Trofeo corona 👑",price:300},
    {id:"star",type:"trophy",name:"Trofeo estrella ⭐",price:250},
    {id:"ball",type:"trophy",name:"Trofeo balón ⚽",price:200}
  ];
  function showShop(){processRewards(false);var u=read();if(!u)return;ensureMeta(u);var o=makeOverlay("shopOverlay","Tienda Chigui");var body=o.querySelector(".hub-body");function render(){u=read();ensureMeta(u);body.innerHTML='<div class="hub-toolbar"><span class="chigui-coin-pill">🪙 '+u.coins+' Chigui Coins</span><span class="muted">Solo cosméticos. Las monedas se ganan jugando y acertando predicciones; no tienen valor real.</span></div><div class="shop-grid">'+shopItems.map(function(i){var owned=i.price===0||!!u.meta.shop.owned[i.id];var active=(i.type==="theme"&&u.meta.shop.activeTheme===i.id)||(i.type==="trophy"&&u.meta.shop.activeTrophy===i.id);return '<div class="shop-card '+(owned?'is-owned':'')+'">'+(i.type==="theme"?'<div class="shop-preview" style="--shop-a:'+i.a+';--shop-b:'+i.b+'"></div>':'<div class="shop-preview" style="display:grid;place-items:center;font-size:2rem">'+(i.id==="crown"?'👑':i.id==="star"?'⭐':'⚽')+'</div>')+'<h3>'+esc(i.name)+'</h3><div class="shop-price">'+(i.price?('🪙 '+i.price):'Gratis')+'</div><div class="shop-actions"><button class="'+(active?'secondary-button':'primary-button')+'" data-shop="'+i.id+'" '+(active?'disabled':'')+'>'+(active?'✅ Equipado':owned?'Usar':'Comprar')+'</button></div></div>';}).join("")+'</div>';body.querySelectorAll("[data-shop]").forEach(function(b){b.addEventListener("click",function(){var item=shopItems.find(function(i){return i.id===b.dataset.shop;});var cur=read();ensureMeta(cur);var owned=item.price===0||cur.meta.shop.owned[item.id];if(!owned){if(cur.coins<item.price){toast("🪙 No tienes suficientes Chigui Coins");return;}cur.coins-=item.price;cur.meta.shop.owned[item.id]=true;}if(item.type==="theme")cur.meta.shop.activeTheme=item.id;else cur.meta.shop.activeTrophy=item.id;write(cur);applyCosmetics(cur);updateWallet(cur);render();});});}render();openOverlay(o);}

  function showSaves(){var o=makeOverlay("savesOverlay","Partidas y copias");var body=o.querySelector(".hub-body");function render(){var active=read();var html='<div class="save-grid">';for(var i=1;i<=3;i++){var raw=localStorage.getItem(SLOT_PREFIX+i),u=null;try{u=raw?JSON.parse(raw):null;}catch(e){}html+='<div class="save-card"><h3>💾 Slot '+i+'</h3><div class="save-meta">'+(u?esc((u.name||"Universo")+' · Copa #'+((u.cup&&u.cup.edition)||1)):'Vacío')+'</div><div class="save-actions"><button class="primary-button" data-save="'+i+'">Guardar</button><button class="secondary-button" data-load="'+i+'" '+(!u?'disabled':'')+'>Cargar</button><button class="secondary-button" data-delete="'+i+'" '+(!u?'disabled':'')+'>Borrar</button></div></div>';}html+='</div><div class="hub-toolbar" style="margin-top:16px"><button id="exportUniverse" class="secondary-button" '+(!active?'disabled':'')+'>⬇️ Exportar universo</button><button id="importUniverse" class="secondary-button">⬆️ Importar universo</button><input id="importUniverseFile" type="file" accept="application/json,.json" class="hidden"></div>';body.innerHTML=html;body.querySelectorAll("[data-save]").forEach(function(b){b.addEventListener("click",function(){var u=read();if(!u)return;localStorage.setItem(SLOT_PREFIX+b.dataset.save,JSON.stringify(u));toast("💾 Partida guardada en slot "+b.dataset.save);render();});});body.querySelectorAll("[data-load]").forEach(function(b){b.addEventListener("click",function(){var raw=localStorage.getItem(SLOT_PREFIX+b.dataset.load);if(raw&&confirm("¿Cargar este universo? La partida activa será reemplazada.")){localStorage.setItem(STORAGE_KEY,raw);location.reload();}});});body.querySelectorAll("[data-delete]").forEach(function(b){b.addEventListener("click",function(){if(confirm("¿Borrar el slot "+b.dataset.delete+"?")){localStorage.removeItem(SLOT_PREFIX+b.dataset.delete);render();}});});var ex=body.querySelector("#exportUniverse");if(ex)ex.addEventListener("click",function(){var u=read();if(!u)return;var blob=new Blob([JSON.stringify(u,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="copa-chigui-"+(u.name||"universo").replace(/[^a-z0-9]+/gi,"-").toLowerCase()+".json";a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);});var imp=body.querySelector("#importUniverse"),file=body.querySelector("#importUniverseFile");imp.addEventListener("click",function(){file.click();});file.addEventListener("change",function(){var f=file.files&&file.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{var u=JSON.parse(r.result);if(!u||!u.cup||!Array.isArray(u.cup.participants))throw new Error();localStorage.setItem(STORAGE_KEY,JSON.stringify(u));location.reload();}catch(e){alert("El archivo no parece ser una partida válida de Copa Chigui.");}};r.readAsText(f);});}render();openOverlay(o);}

  function showSettings(){var u=read();if(!u)return;ensureMeta(u);var o=makeOverlay("settingsOverlay","Ajustes");var body=o.querySelector(".hub-body");function render(){u=read();ensureMeta(u);body.innerHTML='<div class="hub-card"><div class="settings-row"><div><strong>🔊 Sonidos de interfaz</strong><div class="muted">Pequeños sonidos al usar botones.</div></div><button id="toggleSound" class="secondary-button toggle-button">'+(u.meta.settings.sound!==false?'Activado':'Desactivado')+'</button></div><div class="settings-row"><div><strong>✨ Animaciones</strong><div class="muted">Transiciones, simulación y efectos visuales.</div></div><button id="toggleAnimations" class="secondary-button toggle-button">'+(u.meta.settings.animations!==false?'Activadas':'Desactivadas')+'</button></div></div>';body.querySelector("#toggleSound").addEventListener("click",function(){u=read();ensureMeta(u);u.meta.settings.sound=!u.meta.settings.sound;write(u);render();});body.querySelector("#toggleAnimations").addEventListener("click",function(){u=read();ensureMeta(u);u.meta.settings.animations=!u.meta.settings.animations;write(u);applyCosmetics(u);render();});}render();openOverlay(o);}

  function findNext(cup){for(var d=0;d<3;d++){for(var g=0;g<(cup.groups||[]).length;g++){var md=cup.groups[g].matchdays&&cup.groups[g].matchdays[d];if(!md)continue;for(var i=0;i<md.matches.length;i++)if(!md.matches[i].completed)return md.matches[i];}}var rounds=["roundOf32","roundOf16","quarterfinals","semifinals","thirdPlace","final"];for(var r=0;r<rounds.length;r++){var list=cup.knockout&&cup.knockout[rounds[r]]||[];for(var j=0;j<list.length;j++)if(!list[j].completed)return list[j];}return null;}
  function showMatchCenter(){var u=read();if(!u||!u.cup)return;var m=findNext(u.cup);if(!m){toast("No hay un próximo partido pendiente.");return;}var h=byId(u.cup,m.homeId),a=byId(u.cup,m.awayId);if(!h||!a)return;var ranks=u.cup.worldRankingTeams||[],hr=ranks.find(function(t){return t.id===h.id;}),ar=ranks.find(function(t){return t.id===a.id;}),duel=h2h(u,h.id,a.id),pred=u.cup.predictions&&u.cup.predictions.entries&&u.cup.predictions.entries[m.id];var o=makeOverlay("matchCenterOverlay","Centro de partido");var body=o.querySelector(".hub-body");body.innerHTML='<div class="match-center-versus"><div class="match-center-team"><span style="font-size:2.8rem">'+esc(h.flag||"🏳️")+'</span><strong>'+esc(h.name)+'</strong><span>'+esc(h.points)+' pts</span></div><div class="match-center-vs">VS</div><div class="match-center-team"><span style="font-size:2.8rem">'+esc(a.flag||"🏳️")+'</span><strong>'+esc(a.name)+'</strong><span>'+esc(a.points)+' pts</span></div></div><div class="match-center-grid"><div class="hub-card"><h3>📊 Ranking</h3><div class="hub-stat"><span>'+esc(h.name)+'</span><strong>#'+esc(hr&&hr.currentRank||"—")+'</strong></div><div class="hub-stat"><span>'+esc(a.name)+'</span><strong>#'+esc(ar&&ar.currentRank||"—")+'</strong></div></div><div class="hub-card"><h3>⚔️ Cara a cara</h3><div class="hub-stat"><span>'+esc(h.name)+'</span><strong>'+duel.a+'</strong></div><div class="hub-stat"><span>Empates</span><strong>'+duel.d+'</strong></div><div class="hub-stat"><span>'+esc(a.name)+'</span><strong>'+duel.b+'</strong></div></div><div class="hub-card"><h3>🎯 Predicción</h3><p>'+(pred&&pred.player?('Tu marcador: <strong>'+pred.player.home+'-'+pred.player.away+'</strong>'):'Todavía no has guardado una predicción para este partido.')+'</p><p class="muted">La predicción de la IA sigue oculta hasta el resultado.</p></div></div>';openOverlay(o);}

  function showDraw(cup){if(!cup||!cup.groups)return;var old=document.getElementById("drawRevealOverlay");if(old)old.remove();var o=document.createElement("div");o.id="drawRevealOverlay";o.className="draw-overlay";o.innerHTML='<div class="draw-card"><div class="draw-title"><p class="eyebrow">SORTEO OFICIAL</p><h2>'+(window.CopaChiguiTitle?esc(window.CopaChiguiTitle.titleFor(cup)):('Copa Chigui #'+(cup.edition||1)))+'</h2><p class="muted">El anfitrión ocupa siempre A1.</p></div><div class="draw-groups">'+cup.groups.map(function(g,gi){return '<div class="draw-group" style="animation-delay:'+(gi*.045)+'s"><h4>'+esc(g.name)+'</h4>'+g.teams.map(function(t,ti){return '<div class="draw-team '+(t.id===cup.hostId?'is-host':'')+'">'+esc(t.flag||"🏳️")+' '+esc(t.name)+(t.id===cup.hostId&&gi===0&&ti===0?' 🏟️':'')+'</div>';}).join("")+'</div>';}).join("")+'</div><div class="stage-actions"><button id="closeDrawReveal" class="primary-button">Continuar</button></div></div>';document.body.appendChild(o);document.body.style.overflow="hidden";o.querySelector("#closeDrawReveal").addEventListener("click",function(){o.remove();document.body.style.overflow="";});}

  function enhanceMenu(){var grid=mainMenu.querySelector(".main-menu-grid");if(!grid)return;grid.classList.add("is-expanded");if(!document.getElementById("mainWallet")){var w=document.createElement("div");w.id="mainWallet";w.className="main-menu-wallet";w.innerHTML='<span class="chigui-coin-pill">🪙 <span id="mainWalletAmount">0 Chigui Coins</span></span>';mainMenu.querySelector(".main-menu-heading").insertAdjacentElement("afterend",w);}var buttons=Array.prototype.slice.call(grid.querySelectorAll(".main-menu-button"));function named(name){return buttons.find(function(b){var s=b.querySelector("strong");return s&&s.textContent.trim()===name;});}var partidas=named("Partidas"),ajustes=named("Ajustes");if(partidas){partidas.disabled=false;partidas.id="mainSavesButton";partidas.querySelector("small").textContent="Slots, exportar e importar";}if(ajustes){ajustes.disabled=false;ajustes.id="mainSettingsButton";ajustes.querySelector("small").textContent="Sonido, animaciones y apariencia";}function add(id,icon,title,small,fn){if(document.getElementById(id))return;var b=document.createElement("button");b.id=id;b.className="main-menu-button";b.type="button";b.innerHTML='<span class="main-menu-icon">'+icon+'</span><span><strong>'+esc(title)+'</strong><small>'+esc(small)+'</small></span>';b.addEventListener("click",fn);grid.appendChild(b);}add("mainTeamsButton","🌍","Selecciones","Perfiles, estadísticas y cara a cara",showTeams);add("mainRecordsButton","🏅","Récords y premios","Récords, premios, noticias y logros",showRecords);add("mainShopButton","🛒","Tienda Chigui","Gasta tus Chigui Coins en cosméticos",showShop);if(partidas&&!partidas.dataset.hubReady){partidas.dataset.hubReady="1";partidas.addEventListener("click",showSaves);}if(ajustes&&!ajustes.dataset.hubReady){ajustes.dataset.hubReady="1";ajustes.addEventListener("click",showSettings);}updateWallet();}

  var audioCtx=null;document.addEventListener("click",function(e){var b=e.target.closest("button");if(!b)return;var u=read();if(!u){return;}ensureMeta(u);if(u.meta.settings.sound===false)return;try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();var osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.frequency.value=520;gain.gain.value=.025;osc.connect(gain);gain.connect(audioCtx.destination);osc.start();gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.055);osc.stop(audioCtx.currentTime+.06);}catch(err){}},true);

  var form=document.getElementById("newUniverseForm");if(form){form.addEventListener("submit",function(){setTimeout(function(){var u=read();if(u&&u.cup)showDraw(u.cup);processRewards(true);syncAchievements();},120);});}
  var redraw=document.getElementById("newDrawButton");if(redraw){redraw.addEventListener("click",function(){var before=read();var sig=before&&before.cup&&before.cup.createdAt;setTimeout(function(){var u=read();if(u&&u.cup&&u.cup.createdAt!==sig)showDraw(u.cup);},120);});}
  document.addEventListener("click",function(e){if(e.target.closest(".competition-next-card")){showMatchCenter();}},false);

  enhanceMenu();applyCosmetics();processRewards(false);syncAchievements();
  var scheduled=false;new MutationObserver(function(){if(scheduled)return;scheduled=true;setTimeout(function(){scheduled=false;processRewards(false);syncAchievements();updateWallet();},120);}).observe(document.body,{childList:true,subtree:true});
  window.CopaChiguiHub={teams:showTeams,records:showRecords,shop:showShop,saves:showSaves,settings:showSettings,matchCenter:showMatchCenter,draw:showDraw};
}());