window.COPA_CHIGUI_TEAMS = [
  { id: "AFG", name: "Afganistán", flag: "🇦🇫", flagFile: "AFGANISTAN.png" },
  { id: "ALB", name: "Albania", flag: "🇦🇱", flagFile: "ALBANIA.png" },
  { id: "GER", name: "Alemania", flag: "🇩🇪", flagFile: "ALEMANIA.png" },
  { id: "AND", name: "Andorra", flag: "🇦🇩", flagFile: "ANDORRA.png" },
  { id: "AGO", name: "Angola", flag: "🇦🇴", flagFile: "ANGOLA.png" },
  { id: "AIA", name: "Anguila", flag: "🇦🇮", flagFile: "ANGUILA.png" },
  { id: "ATG", name: "Antigua y Barbuda", flag: "🇦🇬", flagFile: "ANTIGUA Y BARBUDA.png" },
  { id: "KSA", name: "Arabia Saudita", flag: "🇸🇦", flagFile: "ARABIA SAUDITA.png" },
  { id: "ALG", name: "Argelia", flag: "🇩🇿", flagFile: "ARGELIA.png" },
  { id: "ARG", name: "Argentina", flag: "🇦🇷", flagFile: "ARGENTINA.png" },
  { id: "ARM", name: "Armenia", flag: "🇦🇲", flagFile: "ARMENIA.png" },
  { id: "ABW", name: "Aruba", flag: "🇦🇼", flagFile: "ARUBA.png" },
  { id: "AUS", name: "Australia", flag: "🇦🇺", flagFile: "AUSTRALIA.png" },
  { id: "AUT", name: "Austria", flag: "🇦🇹", flagFile: "AUSTRIA.png" },
  { id: "AZE", name: "Azerbaiyán", flag: "🇦🇿", flagFile: "AZERBAIYAN.png" },
  { id: "BAH", name: "Bahamas", flag: "🇧🇸", flagFile: "BAHAMAS.png" },
  { id: "BAN", name: "Bangladés", flag: "🇧🇩", flagFile: "BANGLADESH.png" },
  { id: "BRB", name: "Barbados", flag: "🇧🇧", flagFile: "BARBADOS.png" },
  { id: "BHR", name: "Baréin", flag: "🇧🇭", flagFile: "BAREIN.png" },
  { id: "BEL", name: "Bélgica", flag: "🇧🇪", flagFile: "BELGICA.png" },
  { id: "BLZ", name: "Belice", flag: "🇧🇿", flagFile: "BELICE.png" },
  { id: "BEN", name: "Benín", flag: "🇧🇯", flagFile: "BENIN.png" },
  { id: "BER", name: "Bermudas", flag: "🇧🇲", flagFile: "BERMUDAS.png" },
  { id: "BLR", name: "Bielorrusia", flag: "🇧🇾", flagFile: "BIELORRUSIA.png" },
  { id: "BOL", name: "Bolivia", flag: "🇧🇴", flagFile: "BOLIVIA.png" },
  { id: "BON", name: "Bonaire", flag: "🇧🇶", flagFile: "BONAIRE.png" },
  { id: "BIH", name: "Bosnia y Herzegovina", flag: "🇧🇦", flagFile: "BOSNIA Y HERZEGOVINA.png" },
  { id: "BOT", name: "Botsuana", flag: "🇧🇼", flagFile: "BOTSUANA.png" },
  { id: "BRA", name: "Brasil", flag: "🇧🇷", flagFile: "BRASIL.png" },
  { id: "BRU", name: "Brunéi", flag: "🇧🇳", flagFile: "BRUNEI.png" },
  { id: "BUL", name: "Bulgaria", flag: "🇧🇬", flagFile: "BULGARIA.png" },
  { id: "BFA", name: "Burkina Faso", flag: "🇧🇫", flagFile: "BURKINA FASO.png" },
  { id: "BDI", name: "Burundi", flag: "🇧🇮", flagFile: "BURUNDI.png" },
  { id: "BHU", name: "Bután", flag: "🇧🇹", flagFile: "BUTAN.png" },
  { id: "CPV", name: "Cabo Verde", flag: "🇨🇻", flagFile: "CABO VERDE.png" },
  { id: "CAM", name: "Camboya", flag: "🇰🇭", flagFile: "CAMBOYA.png" },
  { id: "CMR", name: "Camerún", flag: "🇨🇲", flagFile: "CAMERUN.png" },
  { id: "CAN", name: "Canadá", flag: "🇨🇦", flagFile: "CANADA.png" },
  { id: "QAT", name: "Catar", flag: "🇶🇦", flagFile: "CATAR.png" },
  { id: "CEU", name: "Ceuta", flag: "🏳️", flagFile: "CEUTA.png" },
  { id: "CHA", name: "Chad", flag: "🇹🇩", flagFile: "CHAD.png" },
  { id: "CZE", name: "Chequia", flag: "🇨🇿", flagFile: "CHEQUIA.png" },
  { id: "CHI", name: "Chile", flag: "🇨🇱", flagFile: "CHILE.png" },
  { id: "CHN", name: "China", flag: "🇨🇳", flagFile: "CHINA.png" },
  { id: "NCP", name: "Chipre del Norte", flag: "🏳️", flagFile: "CHIPRE DEL NORTE.png" },
  { id: "CYP", name: "Chipre", flag: "🇨🇾", flagFile: "CHIPRE.png" },
  { id: "COL", name: "Colombia", flag: "🇨🇴", flagFile: "COLOMBIA.png" },
  { id: "COM", name: "Comoras", flag: "🇰🇲", flagFile: "COMORAS.png" },
  { id: "PRK", name: "Corea del Norte", flag: "🇰🇵", flagFile: "COREA DEL NORTE.png" },
  { id: "KOR", name: "Corea del Sur", flag: "🇰🇷", flagFile: "COREA DEL SUR.png" },
  { id: "CIV", name: "Costa de Marfil", flag: "🇨🇮", flagFile: "COSTA DE MARFIL.png" },
  { id: "CRC", name: "Costa Rica", flag: "🇨🇷", flagFile: "COSTA RICA.png" },
  { id: "CRO", name: "Croacia", flag: "🇭🇷", flagFile: "CROACIA.png" },
  { id: "CUB", name: "Cuba", flag: "🇨🇺", flagFile: "CUBA.png" },
  { id: "CUW", name: "Curazao", flag: "🇨🇼", flagFile: "CURAZAO.png" },
  { id: "DEN", name: "Dinamarca", flag: "🇩🇰", flagFile: "DINAMARCA.png" },
  { id: "DMA", name: "Dominica", flag: "🇩🇲", flagFile: "DOMINICA.png" },
  { id: "ECU", name: "Ecuador", flag: "🇪🇨", flagFile: "ECUADOR.png" },
  { id: "EGY", name: "Egipto", flag: "🇪🇬", flagFile: "EGIPTO.png" },
  { id: "SLV", name: "El Salvador", flag: "🇸🇻", flagFile: "EL SALVADOR.png" },
  { id: "UAE", name: "Emiratos Árabes Unidos", flag: "🇦🇪", flagFile: "EMIRATOS ARABES UNIDOS.png" },
  { id: "ERI", name: "Eritrea", flag: "🇪🇷", flagFile: "ERITREA.png" },
  { id: "SCO", name: "Escocia", flag: "🏴", flagFile: "ESCOCIA.png" },
  { id: "SVK", name: "Eslovaquia", flag: "🇸🇰", flagFile: "ESLOVAQUIA.png" },
  { id: "SVN", name: "Eslovenia", flag: "🇸🇮", flagFile: "ESLOVENIA.png" },
  { id: "ESP", name: "España", flag: "🇪🇸", flagFile: "ESPAÑA.png" },
  { id: "USA", name: "Estados Unidos", flag: "🇺🇸", flagFile: "ESTADOS UNIDOS.png" },
  { id: "EST", name: "Estonia", flag: "🇪🇪", flagFile: "ESTONIA.png" },
  { id: "ETH", name: "Etiopía", flag: "🇪🇹", flagFile: "ETIOPIA.png" },
  { id: "PHI", name: "Filipinas", flag: "🇵🇭", flagFile: "FILIPINAS.png" },
  { id: "FIN", name: "Finlandia", flag: "🇫🇮", flagFile: "FINLANDIA.png" },
  { id: "FIJ", name: "Fiyi", flag: "🇫🇯", flagFile: "FIYI.png" },
  { id: "FRA", name: "Francia", flag: "🇫🇷", flagFile: "FRANCIA.png" },
  { id: "GAB", name: "Gabón", flag: "🇬🇦", flagFile: "GABON.png" },
  { id: "WAL", name: "Gales", flag: "🏴", flagFile: "GALES.png" },
  { id: "GAM", name: "Gambia", flag: "🇬🇲", flagFile: "GAMBIA.png" },
  { id: "GEO", name: "Georgia", flag: "🇬🇪", flagFile: "GEORGIA.png" },
  { id: "GHA", name: "Ghana", flag: "🇬🇭", flagFile: "GHANA.png" },
  { id: "GIB", name: "Gibraltar", flag: "🇬🇮", flagFile: "GIBRALTAR.png" },
  { id: "GRN", name: "Granada", flag: "🇬🇩", flagFile: "GRANADA.png" },
  { id: "GRE", name: "Grecia", flag: "🇬🇷", flagFile: "GRECIA.png" },
  { id: "GRL", name: "Groenlandia", flag: "🇬🇱", flagFile: "GROENLANDIA.png" },
  { id: "GLP", name: "Guadalupe", flag: "🇬🇵", flagFile: "GUADALUPE.png" },
  { id: "GUM", name: "Guam", flag: "🇬🇺", flagFile: "GUAM.png" },
  { id: "GUA", name: "Guatemala", flag: "🇬🇹", flagFile: "GUATEMALA.png" },
  { id: "GGY", name: "Guernsey", flag: "🇬🇬", flagFile: "GUERNSEY.png" },
  { id: "GNB", name: "Guinea-Bisáu", flag: "🇬🇼", flagFile: "GUINEA BISSAU.png" },
  { id: "EQG", name: "Guinea Ecuatorial", flag: "🇬🇶", flagFile: "GUINEA ECUATORIAL.png" },
  { id: "GUI", name: "Guinea", flag: "🇬🇳", flagFile: "GUINEA.png" },
  { id: "GUF", name: "Guayana Francesa", flag: "🇬🇫", flagFile: "GUYANA FRANCESA.png" },
  { id: "GUY", name: "Guyana", flag: "🇬🇾", flagFile: "GUYANA.png" },
  { id: "HAI", name: "Haití", flag: "🇭🇹", flagFile: "HAITI.png" },
  { id: "HON", name: "Honduras", flag: "🇭🇳", flagFile: "HONDURAS.png" },
  { id: "HKG", name: "Hong Kong", flag: "🇭🇰", flagFile: "HONG KONG.png" },
  { id: "HUN", name: "Hungría", flag: "🇭🇺", flagFile: "HUNGRIA.png" },
  { id: "IND", name: "India", flag: "🇮🇳", flagFile: "INDIA.png" },
  { id: "IDN", name: "Indonesia", flag: "🇮🇩", flagFile: "INDONESIA.png" },
  { id: "ENG", name: "Inglaterra", flag: "🏴", flagFile: "INGLATERRA.png" },
  { id: "IRN", name: "Irán", flag: "🇮🇷", flagFile: "IRAN.png" },
  { id: "IRQ", name: "Irak", flag: "🇮🇶", flagFile: "IRAQ.png" },
  { id: "NIR", name: "Irlanda del Norte", flag: "🏴", flagFile: "IRLANDA DEL NORTE.png" },
  { id: "IRL", name: "Irlanda", flag: "🇮🇪", flagFile: "IRLANDA.png" },
  { id: "ASC", name: "Isla Ascensión", flag: "🏳️", flagFile: "ISLA ASCENSION.png" },
  { id: "ISL", name: "Islandia", flag: "🇮🇸", flagFile: "ISLANDIA.png" },
  { id: "ALA", name: "Islas Åland", flag: "🇦🇽", flagFile: "ISLAS ALAND.png" },
  { id: "CAY", name: "Islas Caimán", flag: "🇰🇾", flagFile: "ISLAS CAIMAN.png" },
  { id: "CNA", name: "Islas Canarias", flag: "🏳️", flagFile: "ISLAS CANARIAS.png" },
  { id: "CCK", name: "Islas Cocos", flag: "🇨🇨", flagFile: "ISLAS COCOS.png" },
  { id: "COK", name: "Islas Cook", flag: "🇨🇰", flagFile: "ISLAS COOK.png" },
  { id: "IMN", name: "Isla de Man", flag: "🇮🇲", flagFile: "ISLAS DE MAN.png" },
  { id: "CXR", name: "Isla de Navidad", flag: "🇨🇽", flagFile: "ISLAS DE NAVIDAD.png" },
  { id: "FRO", name: "Islas Feroe", flag: "🇫🇴", flagFile: "ISLAS FEROE.png" },
  { id: "NMI", name: "Islas Marianas del Norte", flag: "🇲🇵", flagFile: "ISLAS MARIANAS DEL NORTE.png" },
  { id: "MHL", name: "Islas Marshall", flag: "🇲🇭", flagFile: "ISLAS MARSHALL.png" },
  { id: "NFK", name: "Isla Norfolk", flag: "🇳🇫", flagFile: "ISLAS NORFOLK.png" },
  { id: "PCN", name: "Islas Pitcairn", flag: "🇵🇳", flagFile: "ISLAS PITCAIRN.png" },
  { id: "SOL", name: "Islas Salomón", flag: "🇸🇧", flagFile: "ISLAS SALOMON.png" },
  { id: "TCA", name: "Islas Turcas y Caicos", flag: "🇹🇨", flagFile: "ISLAS TURCAS Y CAICOS.png" },
  { id: "VGB", name: "Islas Vírgenes Británicas", flag: "🇻🇬", flagFile: "ISLAS VIRGENES BRITANICAS.png" },
  { id: "VIR", name: "Islas Vírgenes Estadounidenses", flag: "🇻🇮", flagFile: "ISLAS VIRGENES ESTADOUNIDENSAS.png" },
  { id: "ISR", name: "Israel", flag: "🇮🇱", flagFile: "ISRAEL.png" },
  { id: "ITA", name: "Italia", flag: "🇮🇹", flagFile: "ITALIA.png" },
  { id: "JAM", name: "Jamaica", flag: "🇯🇲", flagFile: "JAMAICA.png" },
  { id: "JPN", name: "Japón", flag: "🇯🇵", flagFile: "JAPON.png" },
  { id: "JEY", name: "Jersey", flag: "🇯🇪", flagFile: "JERSEY.png" },
  { id: "JOR", name: "Jordania", flag: "🇯🇴", flagFile: "JORDANIA.png" },
  { id: "KAZ", name: "Kazajistán", flag: "🇰🇿", flagFile: "KAZAJISTAN.png" },
  { id: "KEN", name: "Kenia", flag: "🇰🇪", flagFile: "KENIA.png" },
  { id: "KGZ", name: "Kirguistán", flag: "🇰🇬", flagFile: "KIRGUISTAN.png" },
  { id: "KIR", name: "Kiribati", flag: "🇰🇮", flagFile: "KIRIBATI.png" },
  { id: "KOS", name: "Kosovo", flag: "🇽🇰", flagFile: "KOSOVO.png" },
  { id: "KUW", name: "Kuwait", flag: "🇰🇼", flagFile: "KUWAIT.png" },
  { id: "LAO", name: "Laos", flag: "🇱🇦", flagFile: "LAOS.png" },
  { id: "LES", name: "Lesoto", flag: "🇱🇸", flagFile: "LESOTO.png" },
  { id: "LVA", name: "Letonia", flag: "🇱🇻", flagFile: "LETONIA.png" },
  { id: "LBN", name: "Líbano", flag: "🇱🇧", flagFile: "LIBANO.png" },
  { id: "LBR", name: "Liberia", flag: "🇱🇷", flagFile: "LIBERIA.png" },
  { id: "LBY", name: "Libia", flag: "🇱🇾", flagFile: "LIBIA.png" },
  { id: "LIE", name: "Liechtenstein", flag: "🇱🇮", flagFile: "LIECHTENSTEIN.png" },
  { id: "LTU", name: "Lituania", flag: "🇱🇹", flagFile: "LITUANIA.png" },
  { id: "LUX", name: "Luxemburgo", flag: "🇱🇺", flagFile: "LUXEMBURGO.png" },
  { id: "MAC", name: "Macao", flag: "🇲🇴", flagFile: "MACAO.png" },
  { id: "MKD", name: "Macedonia del Norte", flag: "🇲🇰", flagFile: "MACEDONIA DEL NORTE.png" },
  { id: "MAD", name: "Madagascar", flag: "🇲🇬", flagFile: "MADAGASCAR.png" },
  { id: "MAS", name: "Malasia", flag: "🇲🇾", flagFile: "MALASIA.png" },
  { id: "MWI", name: "Malawi", flag: "🇲🇼", flagFile: "MALAWI.png" },
  { id: "MDV", name: "Maldivas", flag: "🇲🇻", flagFile: "MALDIVAS.png" },
  { id: "MLI", name: "Malí", flag: "🇲🇱", flagFile: "MALI.png" },
  { id: "MLT", name: "Malta", flag: "🇲🇹", flagFile: "MALTA.png" },
  { id: "MAR", name: "Marruecos", flag: "🇲🇦", flagFile: "MARRUECOS.png" },
  { id: "MTQ", name: "Martinica", flag: "🇲🇶", flagFile: "MARTINICA.png" },
  { id: "MRI", name: "Mauricio", flag: "🇲🇺", flagFile: "MAURICIO.png" },
  { id: "MTN", name: "Mauritania", flag: "🇲🇷", flagFile: "MAURITANIA.png" },
  { id: "MYT", name: "Mayotte", flag: "🇾🇹", flagFile: "MAYOTTE.png" },
  { id: "MEL", name: "Melilla", flag: "🏳️", flagFile: "MELILLA.png" },
  { id: "MEX", name: "México", flag: "🇲🇽", flagFile: "MEXICO.png" },
  { id: "FSM", name: "Micronesia", flag: "🇫🇲", flagFile: "MICRONESIA.png" },
  { id: "MDA", name: "Moldavia", flag: "🇲🇩", flagFile: "MOLDAVIA.png" },
  { id: "MON", name: "Mónaco", flag: "🇲🇨", flagFile: "MONACO.png" },
  { id: "MNG", name: "Mongolia", flag: "🇲🇳", flagFile: "MONGOLIA.png" },
  { id: "MNE", name: "Montenegro", flag: "🇲🇪", flagFile: "MONTENEGRO.png" },
  { id: "MSR", name: "Montserrat", flag: "🇲🇸", flagFile: "MONTSERRAT.png" },
  { id: "MOZ", name: "Mozambique", flag: "🇲🇿", flagFile: "MOZAMBIQUE.png" },
  { id: "MYA", name: "Myanmar", flag: "🇲🇲", flagFile: "MYANMAR.png" },
  { id: "NAM", name: "Namibia", flag: "🇳🇦", flagFile: "NAMIBIA.png" },
  { id: "NRU", name: "Nauru", flag: "🇳🇷", flagFile: "NAURU.png" },
  { id: "NEP", name: "Nepal", flag: "🇳🇵", flagFile: "NEPAL.png" },
  { id: "NIC", name: "Nicaragua", flag: "🇳🇮", flagFile: "NICARAGUA.png" },
  { id: "NIG", name: "Níger", flag: "🇳🇪", flagFile: "NIGER.png" },
  { id: "NGA", name: "Nigeria", flag: "🇳🇬", flagFile: "NIGERIA.png" },
  { id: "NIU", name: "Niue", flag: "🇳🇺", flagFile: "NIUE.png" },
  { id: "NOR", name: "Noruega", flag: "🇳🇴", flagFile: "NORUEGA.png" },
  { id: "NCL", name: "Nueva Caledonia", flag: "🇳🇨", flagFile: "NUEVA CALEDONIA.png" },
  { id: "NZL", name: "Nueva Zelanda", flag: "🇳🇿", flagFile: "NUEVA ZELANDA.png" },
  { id: "OMA", name: "Omán", flag: "🇴🇲", flagFile: "OMAN.png" },
  { id: "NED", name: "Países Bajos", flag: "🇳🇱", flagFile: "PAISES BAJOS.png" },
  { id: "PAK", name: "Pakistán", flag: "🇵🇰", flagFile: "PAKISTAN.png" },
  { id: "PLW", name: "Palaos", flag: "🇵🇼", flagFile: "PALAOS.png" },
  { id: "PLE", name: "Palestina", flag: "🇵🇸", flagFile: "PALESTINA.png" },
  { id: "PAN", name: "Panamá", flag: "🇵🇦", flagFile: "PANAMA.png" },
  { id: "PNG", name: "Papúa Nueva Guinea", flag: "🇵🇬", flagFile: "PAPUA NUEVA GUINEA.png" },
  { id: "PAR", name: "Paraguay", flag: "🇵🇾", flagFile: "PARAGUAY.png" },
  { id: "PER", name: "Perú", flag: "🇵🇪", flagFile: "PERU.png" },
  { id: "TAH", name: "Polinesia Francesa", flag: "🇵🇫", flagFile: "POLINESIA FRANCESA.png" },
  { id: "POL", name: "Polonia", flag: "🇵🇱", flagFile: "POLONIA.png" },
  { id: "POR", name: "Portugal", flag: "🇵🇹", flagFile: "PORTUGAL.png" },
  { id: "PUR", name: "Puerto Rico", flag: "🇵🇷", flagFile: "PUERTO RICO.png" },
  { id: "GBR", name: "Reino Unido", flag: "🇬🇧", flagFile: "REINO UNIDO.png" },
  { id: "CTA", name: "República Centroafricana", flag: "🇨🇫", flagFile: "REPUBLICA CENTROAFRICANA.png" },
  { id: "CGO", name: "República del Congo", flag: "🇨🇬", flagFile: "REPUBLICA DEL CONGO.png" },
  { id: "COD", name: "República Democrática del Congo", flag: "🇨🇩", flagFile: "REPUBLICA DEMOCRATICA DEL CONGO.png" },
  { id: "DOM", name: "República Dominicana", flag: "🇩🇴", flagFile: "REPUBLICA DOMINICANA.png" },
  { id: "REU", name: "Reunión", flag: "🇷🇪", flagFile: "REUNION.png" },
  { id: "RWA", name: "Ruanda", flag: "🇷🇼", flagFile: "RUANDA.png" },
  { id: "ROU", name: "Rumania", flag: "🇷🇴", flagFile: "RUMANIA.png" },
  { id: "RUS", name: "Rusia", flag: "🇷🇺", flagFile: "RUSIA.png" },
  { id: "SAB", name: "Saba", flag: "🇧🇶", flagFile: "SABA.png" },
  { id: "ESH", name: "Sáhara Occidental", flag: "🇪🇭", flagFile: "SAHARA OCCIDENTAL.png" },
  { id: "ASA", name: "Samoa Americana", flag: "🇦🇸", flagFile: "SAMOA AMERICANA.png" },
  { id: "SAM", name: "Samoa", flag: "🇼🇸", flagFile: "SAMOA.png" },
  { id: "BLM", name: "San Bartolomé", flag: "🇧🇱", flagFile: "SAN BARTOLOME.png" },
  { id: "SKN", name: "San Cristóbal y Nieves", flag: "🇰🇳", flagFile: "SAN CRISTOBAL Y NIEVES.png" },
  { id: "STE", name: "San Eustaquio", flag: "🇧🇶", flagFile: "SAN EUSTAQUIO.png" },
  { id: "SMR", name: "San Marino", flag: "🇸🇲", flagFile: "SAN MARINO.png" },
  { id: "MAF", name: "San Martín", flag: "🇲🇫", flagFile: "SAN MARTIN.png" },
  { id: "VIN", name: "San Vicente y las Granadinas", flag: "🇻🇨", flagFile: "SAN VICENTE Y LAS GRANADINAS.png" },
  { id: "SHN", name: "Santa Elena", flag: "🇸🇭", flagFile: "SANTA ELENA.png" },
  { id: "LCA", name: "Santa Lucía", flag: "🇱🇨", flagFile: "SANTA LUCIA.png" },
  { id: "STP", name: "Santo Tomé y Príncipe", flag: "🇸🇹", flagFile: "SANTO TOME Y PRINCIPE.png" },
  { id: "SEN", name: "Senegal", flag: "🇸🇳", flagFile: "SENEGAL.png" },
  { id: "SRB", name: "Serbia", flag: "🇷🇸", flagFile: "SERBIA.png" },
  { id: "SEY", name: "Seychelles", flag: "🇸🇨", flagFile: "SEYCHELLES.png" },
  { id: "SLE", name: "Sierra Leona", flag: "🇸🇱", flagFile: "SIERRA LEONA.png" },
  { id: "SIN", name: "Singapur", flag: "🇸🇬", flagFile: "SINGAPUR.png" },
  { id: "SYR", name: "Siria", flag: "🇸🇾", flagFile: "SIRIA.png" },
  { id: "SOM", name: "Somalia", flag: "🇸🇴", flagFile: "SOMALIA.png" },
  { id: "SML", name: "Somalilandia", flag: "🏳️", flagFile: "SOMALILANDIA.png" },
  { id: "SRI", name: "Sri Lanka", flag: "🇱🇰", flagFile: "SRI LANKA.png" },
  { id: "SWZ", name: "Suazilandia", flag: "🇸🇿", flagFile: "SUAZILANDIA.png" },
  { id: "RSA", name: "Sudáfrica", flag: "🇿🇦", flagFile: "SUDAFRICA.png" },
  { id: "SSD", name: "Sudán del Sur", flag: "🇸🇸", flagFile: "SUDAN DEL SUR.png" },
  { id: "SDN", name: "Sudán", flag: "🇸🇩", flagFile: "SUDAN.png" },
  { id: "SWE", name: "Suecia", flag: "🇸🇪", flagFile: "SUECIA.png" },
  { id: "SUI", name: "Suiza", flag: "🇨🇭", flagFile: "SUIZA.png" },
  { id: "SUR", name: "Surinam", flag: "🇸🇷", flagFile: "SURINAM.png" },
  { id: "THA", name: "Tailandia", flag: "🇹🇭", flagFile: "TAILANDIA.png" },
  { id: "TPE", name: "Taiwán", flag: "🇹🇼", flagFile: "TAIWAN.png" },
  { id: "TAN", name: "Tanzania", flag: "🇹🇿", flagFile: "TANZANIA.png" },
  { id: "TJK", name: "Tayikistán", flag: "🇹🇯", flagFile: "TAYIKISTAN.png" },
  { id: "TLS", name: "Timor Oriental", flag: "🇹🇱", flagFile: "TIMOR ORIENTAL.png" },
  { id: "TOG", name: "Togo", flag: "🇹🇬", flagFile: "TOGO.png" },
  { id: "TKL", name: "Tokelau", flag: "🇹🇰", flagFile: "TOKELAU.png" },
  { id: "TGA", name: "Tonga", flag: "🇹🇴", flagFile: "TONGA.png" },
  { id: "TRI", name: "Trinidad y Tobago", flag: "🇹🇹", flagFile: "TRINIDAD Y TOBAGO.png" },
  { id: "TAA", name: "Tristán de Acuña", flag: "🏳️", flagFile: "TRISTAN DE ACUÑA.png" },
  { id: "TUN", name: "Túnez", flag: "🇹🇳", flagFile: "TUNEZ.png" },
  { id: "TKM", name: "Turkmenistán", flag: "🇹🇲", flagFile: "TURKMENISTAN.png" },
  { id: "TUR", name: "Turquía", flag: "🇹🇷", flagFile: "TURQUIA.png" },
  { id: "TUV", name: "Tuvalu", flag: "🇹🇻", flagFile: "TUVALU.png" },
  { id: "UKR", name: "Ucrania", flag: "🇺🇦", flagFile: "UCRANIA.png" },
  { id: "UGA", name: "Uganda", flag: "🇺🇬", flagFile: "UGANDA.png" },
  { id: "URU", name: "Uruguay", flag: "🇺🇾", flagFile: "URUGUAY.png" },
  { id: "UZB", name: "Uzbekistán", flag: "🇺🇿", flagFile: "UZBEKISTAN.png" },
  { id: "VAT", name: "Vaticano", flag: "🇻🇦", flagFile: "VATICANO.png" },
  { id: "VEN", name: "Venezuela", flag: "🇻🇪", flagFile: "VENEZUELA.png" },
  { id: "VIE", name: "Vietnam", flag: "🇻🇳", flagFile: "VIETNAM.png" },
  { id: "VAN", name: "Vanuatu", flag: "🇻🇺", flagFile: "VUNUATU.png" },
  { id: "WLF", name: "Wallis y Futuna", flag: "🇼🇫", flagFile: "WALLIS Y FUTUNA.png" },
  { id: "YEM", name: "Yemen", flag: "🇾🇪", flagFile: "YEMEN.png" },
  { id: "DJI", name: "Yibuti", flag: "🇩🇯", flagFile: "YIBUTI.png" },
  { id: "ZAM", name: "Zambia", flag: "🇿🇲", flagFile: "ZAMBIA.png" },
  { id: "ZIM", name: "Zimbabue", flag: "🇿🇼", flagFile: "ZIMBABUE.png" }
].map(function (team) {
  return Object.assign({ points: 100, titles: 0 }, team);
});
