window.COPA_CHIGUI_TEAMS = [
  { id: "GUA", name: "Guatemala", flag: "🇬🇹" },
  { id: "MEX", name: "México", flag: "🇲🇽" },
  { id: "USA", name: "Estados Unidos", flag: "🇺🇸" },
  { id: "CAN", name: "Canadá", flag: "🇨🇦" },
  { id: "CRC", name: "Costa Rica", flag: "🇨🇷" },
  { id: "PAN", name: "Panamá", flag: "🇵🇦" },
  { id: "HON", name: "Honduras", flag: "🇭🇳" },
  { id: "SLV", name: "El Salvador", flag: "🇸🇻" },
  { id: "NIC", name: "Nicaragua", flag: "🇳🇮" },
  { id: "JAM", name: "Jamaica", flag: "🇯🇲" },
  { id: "HAI", name: "Haití", flag: "🇭🇹" },
  { id: "DOM", name: "República Dominicana", flag: "🇩🇴" },
  { id: "CUB", name: "Cuba", flag: "🇨🇺" },
  { id: "TRI", name: "Trinidad y Tobago", flag: "🇹🇹" },
  { id: "ARG", name: "Argentina", flag: "🇦🇷" },
  { id: "BRA", name: "Brasil", flag: "🇧🇷" },
  { id: "URU", name: "Uruguay", flag: "🇺🇾" },
  { id: "PAR", name: "Paraguay", flag: "🇵🇾" },
  { id: "CHI", name: "Chile", flag: "🇨🇱" },
  { id: "PER", name: "Perú", flag: "🇵🇪" },
  { id: "ECU", name: "Ecuador", flag: "🇪🇨" },
  { id: "COL", name: "Colombia", flag: "🇨🇴" },
  { id: "VEN", name: "Venezuela", flag: "🇻🇪" },
  { id: "BOL", name: "Bolivia", flag: "🇧🇴" },

  { id: "ESP", name: "España", flag: "🇪🇸" },
  { id: "FRA", name: "Francia", flag: "🇫🇷" },
  { id: "GER", name: "Alemania", flag: "🇩🇪" },
  { id: "ITA", name: "Italia", flag: "🇮🇹" },
  { id: "ENG", name: "Inglaterra", flag: "🏴" },
  { id: "POR", name: "Portugal", flag: "🇵🇹" },
  { id: "NED", name: "Países Bajos", flag: "🇳🇱" },
  { id: "BEL", name: "Bélgica", flag: "🇧🇪" },
  { id: "CRO", name: "Croacia", flag: "🇭🇷" },
  { id: "SRB", name: "Serbia", flag: "🇷🇸" },
  { id: "POL", name: "Polonia", flag: "🇵🇱" },
  { id: "DEN", name: "Dinamarca", flag: "🇩🇰" },
  { id: "SWE", name: "Suecia", flag: "🇸🇪" },
  { id: "NOR", name: "Noruega", flag: "🇳🇴" },
  { id: "FIN", name: "Finlandia", flag: "🇫🇮" },
  { id: "ISL", name: "Islandia", flag: "🇮🇸" },
  { id: "IRL", name: "Irlanda", flag: "🇮🇪" },
  { id: "SUI", name: "Suiza", flag: "🇨🇭" },
  { id: "AUT", name: "Austria", flag: "🇦🇹" },
  { id: "GRE", name: "Grecia", flag: "🇬🇷" },
  { id: "TUR", name: "Turquía", flag: "🇹🇷" },
  { id: "UKR", name: "Ucrania", flag: "🇺🇦" },
  { id: "ROU", name: "Rumania", flag: "🇷🇴" },
  { id: "BUL", name: "Bulgaria", flag: "🇧🇬" },

  { id: "JPN", name: "Japón", flag: "🇯🇵" },
  { id: "KOR", name: "Corea del Sur", flag: "🇰🇷" },
  { id: "CHN", name: "China", flag: "🇨🇳" },
  { id: "IND", name: "India", flag: "🇮🇳" },
  { id: "IDN", name: "Indonesia", flag: "🇮🇩" },
  { id: "MAS", name: "Malasia", flag: "🇲🇾" },
  { id: "PHI", name: "Filipinas", flag: "🇵🇭" },
  { id: "THA", name: "Tailandia", flag: "🇹🇭" },
  { id: "VIE", name: "Vietnam", flag: "🇻🇳" },
  { id: "UZB", name: "Uzbekistán", flag: "🇺🇿" },
  { id: "KAZ", name: "Kazajistán", flag: "🇰🇿" },
  { id: "GEO", name: "Georgia", flag: "🇬🇪" },
  { id: "IRN", name: "Irán", flag: "🇮🇷" },
  { id: "IRQ", name: "Irak", flag: "🇮🇶" },
  { id: "JOR", name: "Jordania", flag: "🇯🇴" },
  { id: "PLE", name: "Palestina", flag: "🇵🇸" },
  { id: "ISR", name: "Israel", flag: "🇮🇱" },
  { id: "KSA", name: "Arabia Saudita", flag: "🇸🇦" },
  { id: "QAT", name: "Catar", flag: "🇶🇦" },

  { id: "MAR", name: "Marruecos", flag: "🇲🇦" },
  { id: "ALG", name: "Argelia", flag: "🇩🇿" },
  { id: "TUN", name: "Túnez", flag: "🇹🇳" },
  { id: "EGY", name: "Egipto", flag: "🇪🇬" },
  { id: "SEN", name: "Senegal", flag: "🇸🇳" },
  { id: "GHA", name: "Ghana", flag: "🇬🇭" },
  { id: "NGA", name: "Nigeria", flag: "🇳🇬" },
  { id: "CMR", name: "Camerún", flag: "🇨🇲" },
  { id: "CIV", name: "Costa de Marfil", flag: "🇨🇮" },
  { id: "MLI", name: "Malí", flag: "🇲🇱" },
  { id: "BFA", name: "Burkina Faso", flag: "🇧🇫" },
  { id: "BEN", name: "Benín", flag: "🇧🇯" },
  { id: "GAM", name: "Gambia", flag: "🇬🇲" },
  { id: "MOZ", name: "Mozambique", flag: "🇲🇿" },
  { id: "NAM", name: "Namibia", flag: "🇳🇦" },
  { id: "ZAM", name: "Zambia", flag: "🇿🇲" },
  { id: "TAN", name: "Tanzania", flag: "🇹🇿" },
  { id: "KEN", name: "Kenia", flag: "🇰🇪" },
  { id: "ETH", name: "Etiopía", flag: "🇪🇹" },
  { id: "RSA", name: "Sudáfrica", flag: "🇿🇦" },

  { id: "AUS", name: "Australia", flag: "🇦🇺" },
  { id: "NZL", name: "Nueva Zelanda", flag: "🇳🇿" },
  { id: "FIJ", name: "Fiyi", flag: "🇫🇯" },
  { id: "SOL", name: "Islas Salomón", flag: "🇸🇧" },
  { id: "VAN", name: "Vanuatu", flag: "🇻🇺" },
  { id: "SAM", name: "Samoa", flag: "🇼🇸" },
  { id: "TGA", name: "Tonga", flag: "🇹🇴" },
  { id: "PNG", name: "Papúa Nueva Guinea", flag: "🇵🇬" },
  { id: "MHL", name: "Islas Marshall", flag: "🇲🇭" },
  { id: "ASA", name: "Samoa Americana", flag: "🇦🇸" }
].map(function (team) {
  return Object.assign({ points: 100, titles: 0 }, team);
});
